In [1]:
from pathlib import Path
import matplotlib.pyplot as plt
import numpy as np
%matplotlib notebook
from sklearn import svm, metrics, datasets
from sklearn.utils import Bunch
from sklearn.model_selection import GridSearchCV, train_test_split

from skimage.io import imread
from skimage.transform import resize
import skimage

c:\Users\alfin\anaconda3\Lib\site-packages\paramiko\transport.py:219: CryptographyDeprecationWarning: Blowfish has been deprecated
  "class": algorithms.Blowfish,


In [2]:
def load_image_files(container_path, dimension=(104, 104)):
    
    image_dir = Path(container_path)
    folders = [directory for directory in image_dir.iterdir() if directory.is_dir()]
    categories = [fo.name for fo in folders]
    descr = "A Rice Disease detection using SVM"
    images = []
    flat_data = []
    target = []
    for i, direc in enumerate(folders):
        for file in direc.iterdir():
            img = skimage.io.imread(file)
            img_resized = resize(img, dimension, anti_aliasing=True, mode='reflect')
            flat_data.append(img_resized.flatten()) 
            images.append(img_resized)
            target.append(i)

    flat_data = np.array(flat_data)
    target = np.array(target)
    images = np.array(images)
    return Bunch(data=flat_data,
                 target=target,
                 target_names=categories,
                 images=images,
                 DESCR=descr)

In [6]:
image_dataset = load_image_files("C:/Users/alfin/Downloads/archive/rice_leaf_diseases") #Load here dataset
print(image_dataset.target_names)

['Bacterial leaf blight', 'Brown spot', 'Leaf smut']


In [7]:
print(image_dataset.target_names)

['Bacterial leaf blight', 'Brown spot', 'Leaf smut']


In [8]:
X_train, X_test, y_train, y_test = train_test_split(image_dataset.data, image_dataset.target, test_size=0.3,random_state=109)
param_grid = [
  {'C': [1, 10, 100, 1000], 'kernel': ['linear']},
  {'C': [1, 10, 100, 1000], 'gamma': [0.001, 0.0001], 'kernel': ['rbf']},
 ]
svc = svm.SVC()
clf = GridSearchCV(svc, param_grid)
clf.fit(X_train, y_train)

GridSearchCV(estimator=SVC(),
             param_grid=[{'C': [1, 10, 100, 1000], 'kernel': ['linear']},
                         {'C': [1, 10, 100, 1000], 'gamma': [0.001, 0.0001],
                          'kernel': ['rbf']}])

In [9]:
y_pred = clf.predict(X_test)

In [10]:
print(clf.score(X_test,y_test))

0.8055555555555556


In [11]:
print("Classification report for - \n{}:\n{}\n".format(
    clf, metrics.classification_report(y_test, y_pred)))

Classification report for - 
GridSearchCV(estimator=SVC(),
             param_grid=[{'C': [1, 10, 100, 1000], 'kernel': ['linear']},
                         {'C': [1, 10, 100, 1000], 'gamma': [0.001, 0.0001],
                          'kernel': ['rbf']}]):
              precision    recall  f1-score   support

           0       0.83      0.83      0.83        12
           1       0.70      0.88      0.78         8
           2       0.86      0.75      0.80        16

    accuracy                           0.81        36
   macro avg       0.80      0.82      0.80        36
weighted avg       0.81      0.81      0.81        36




In [12]:
from sklearn.metrics import confusion_matrix

In [13]:
cm = confusion_matrix(y_test,y_pred)
print(cm)

[[10  1  1]
 [ 0  7  1]
 [ 2  2 12]]


In [14]:
print(y_pred)

[2 0 2 2 2 0 0 2 1 2 0 2 1 1 2 0 0 2 0 2 1 1 0 0 0 0 2 2 1 1 1 1 1 2 2 0]


In [15]:
from PIL import Image
import os
def load_image(file):
    dimension=(104, 104)
    image = Image.open(file)
    flat_data = []
    img = skimage.io.imread(file)
    img_resized = resize(img, dimension, anti_aliasing=True, mode='reflect')
    flat_data.append(img_resized.flatten()) 
    return image,flat_data

In [37]:
import pickle
# now you can save it to a file
with open(r"C:/Users/alfin/Downloads/Rice_Disease_prediction_GUI-master/Rice_Disease_prediction_GUI-master/model/rice_pred.pkl", 'wb') as f:
    pickle.dump(clf, f)

In [38]:

with open(r"C:/Users/alfin/Downloads/Rice_Disease_prediction_GUI-master/Rice_Disease_prediction_GUI-master/model/rice_pred.pkl", 'rb') as f:
    clf1 = pickle.load(f)

In [40]:
import sklearn
print(sklearn.__version__)

1.2.2
